### ISSUE TITLE
NPM package does not include all necessary components. 

### ISSUE THREAD

**Issue by Rodomeista** [doctolib/react-router-transitions#11]
After running `npm install --save-dev react-router-transitions`, not all of the required components are being included. After taking a look at the contents in node_modules/react-router-transitions/lib/index.js, there is no declaration for useTransitions. useTransitions.js is also not included within lib, whereas I see it in the git repo.

**Comment by oliviertassinari** [comment]
This issue should be fixed with a simple release. I will try to do it tomorrow.

**Comment by oliviertassinari** [comment]
I have just published `v0.2.1`.
