### ISSUE TITLE
Is not I have less JS file？

### ISSUE THREAD

**Issue by Chaunjie** [doctolib/react-router-transitions#15]
![image](https://cloud.githubusercontent.com/assets/12093709/20618789/ff790a24-b32b-11e6-93b3-ddd4e17e6072.png)
Is not I have less JS file？

**Comment by oliviertassinari** [comment]
What version of react-router are you using? Can you share the code raising this issue?

**Comment by Chaunjie** [comment]
1.0.3

**Comment by oliviertassinari** [comment]
This API was introduced in `v2.3.0`. We miss a peer dependency here @neoziro.

**Comment by Chaunjie** [comment]
ok, thanks I change to v2.3.0
